---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-web-app-blue
  labels:
    app: simple-web-app
    version: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-web-app
      version: blue
  template:
    metadata:
      labels:
        app: simple-web-app
        version: blue
    spec:
      containers:
      - name: simple-web-app
        image: YOUR_DOCKERHUB_USERNAME/simple-web-app:blue
        ports:
        - containerPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-web-app-green
  labels:
    app: simple-web-app
    version: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-web-app
      version: green
  template:
    metadata:
      labels:
        app: simple-web-app
        version: green
    spec:
      containers:
      - name: simple-web-app
        image: YOUR_DOCKERHUB_USERNAME/simple-web-app:green
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: simple-web-app
spec:
  selector:
    app: simple-web-app
    version: blue  # Initially pointing to the blue version
  ports:
  - port: 80
    targetPort: 3000
  type: NodePort
